### PR TITLE
Update ascii to version 0.7

### PR DESCRIPTION
**Pull request by tomprogrammer**
These are some rather simple changes to update the ascii crate to the latest version.

### CODE REVIEW

**Comment by frewsxcv** [comment]
It looks like `examples/serve-root.rs` relies on the old ascii version. Could you update that file as well? If not I can update it later

**Comment by tomprogrammer** [comment]
I force-pushed the changes. Somehow I forgot to check the examples and tests..

**Comment by tomaka** [comment]
It looks like `ascii` is now part of the stdlib, except that I'm not sure if all the features are present. If so, then we should eventually use it instead.
But for now that PR looks good.

**Comment by tomprogrammer** [comment]
Yes, the `std::ascii::AsciiExt` trait is for "ASCII-subset only operations on string slices". The difference between the `ascii` crate and the trait in the standard library is, that `ascii` can guarantee the encoding of the entire string, like `str` guarantees it for UTF-8.

The `Header` struct encodes the requirement of ascii-only values in the type `AsciiString` for the `value` field. Instead using the `AsciiExt` trait there have to be more checks throughout the code.
Things like `php.stderr.clone().as_ascii_str()` certainly could be rewritten using `AsciiExt::is_ascii()`.

**Comment by frewsxcv** [comment]
Thanks!

**Pull request merged**
