### PR TITLE
Implement HTTPS

### LINKED ISSUE #11: Support for HTTPS
This is a long-term issue. Don't expect it to be implemented within a few weeks or months.

### PR DESCRIPTION
**Pull request by tomaka**
Close #11 

It's nothing difficult. The only bit that is not implemented is the API. I'm waiting for a review of #106 to decide what to do next.

### CODE REVIEW

**Comment by tomaka** [comment]
This should now be good to go.

There is one unresolved question: what to do if the client connects to an SSL server?
To my surprise, OpenSSL generates an error if a client tries to connect to an SSL server through regular HTTP.

I tried sniffing packets from real HTTPS websites to see what's going on, but it looks like the browser will automatically use SSL if you use port 443, even if you type `http://example.com:443`.

**Comment by tomaka** [comment]
I discussed a bit, and the unresolved question is in fact not a problem. If you try to connect to `https://google.fr:80` or `http://google.fr:443` with an older browser you get an error from the server for both.

**Comment by frewsxcv** [comment]
FYI, travis is failing

**Comment by frewsxcv** [comment]
I have some nitpicky comments, but no point in holding this up for them right now. Thanks!

**Pull request merged**
