### PR TITLE
Convert Request constructor function to static method

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by tomaka** [comment]
It was non-static so that it's private.
Currently users can't create a `Request` themselves.

**Comment by frewsxcv** [comment]
1. Methods can be private
2. The function is currently public in master

**Comment by frewsxcv** [comment]
Ah, the `request` module is private, nevermind

**Comment by tomaka** [comment]
Yeah the function is public and the module is private. So other modules can still access the function, but not the outside of the library.

**Pull request closed without merging**
